- name: Setting-up webserver
  hosts: all
  tasks:
- name: Installing httpd software
        package:
                name: "httpd"
                state: present
- name: Starting httpd services
        service:
                name: "httpd"
                state: started
                enabled: yes
